# Generated by Django 2.1.5 on 2020-04-26 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200427_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='status',
        ),
    ]
