# Generated by Django 2.1.5 on 2020-04-27 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_choices_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='title',
            new_name='text',
        ),
    ]
